- Example/KommunicateCore-iOS-SDK.xcodeproj/project.pbxproj
- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Target Support Files/KommunicateCore-iOS-SDK/KommunicateCore-iOS-SDK-Info.plist
- KommunicateCore-iOS-SDK.podspec
- Sources/KommunicateCore-iOS-SDK/Classes/applozickit/ALMQTTConversationService.m
- Sources/KommunicateCore-iOS-SDK/Classes/include/ALMQTTConversationService.h
Agent's Away/Online status change is not updated in realtime in iOS agent app when we change the status on dashboard.
Locally tested by using the callback
> [CM-758] Added Feature for real-time update of user away online status

- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Target Support Files/KommunicateCore-iOS-SDK/KommunicateCore-iOS-SDK-Info.plist
- KommunicateCore-iOS-SDK.podspec
- increased sdk version to 1.0.1
> Increased podspec version for Release

- CHANGELOG.md
- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Target Support Files/KommunicateCore-iOS-SDK/KommunicateCore-iOS-SDK-Info.plist
- KommunicateCore-iOS-SDK.podspec
- Updated pod version to 1.0.4
- updated changelog
> updated version to 1.0.4 & update changelog

- CHANGELOG.md
- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Target Support Files/KommunicateCore-iOS-SDK/KommunicateCore-iOS-SDK-Info.plist
- KommunicateCore-iOS-SDK.podspec
- Updated KM Core pod version to 1.0.5
- Updated Changelog
> Upgrade KMCore Version 1.0.5

- CHANGELOG.md
- Sources/channel/ALChannelClientService.m
- Sources/channel/ALChannelSyncResponse.m
- Updated Channel Sync API to v5 & handled response as per new schema
> [CM-1064] Updated Channel sync api to V5

- CHANGELOG.md
- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Pods.xcodeproj/project.pbxproj
- Example/Pods/Target Support Files/KommunicateCore-iOS-SDK/KommunicateCore-iOS-SDK-Info.plist
- KommunicateCore-iOS-SDK.podspec
- upgraded version to 1.0.6
- updated changelog
> release changes for version

- Sources/include/ALApplozicSettings.h
- Sources/prefrence/ALApplozicSettings.m
-Added methods to store custom bot id & custom bot name in local to help the bot name cusotmization
> [CM-1167] Added methods to store custom bot id & name in local

- Sources/include/ALApplozicSettings.h
- Sources/prefrence/ALApplozicSettings.m
- Added helper method to store the last zendesk conversation id
> [CM-1217] Zendesk Authentication & Single Chat Session

- Sources/include/ALApplozicSettings.h
- Sources/prefrence/ALApplozicSettings.m
- Created helper functions to save & retrieve the last sync time of chat logs which is observed from zendesk
> [CM-1191] Created Helper functions to save to last sync time

- CHANGELOG.md
- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Target Support Files/KommunicateCore-iOS-SDK/KommunicateCore-iOS-SDK-Info.plist
- KommunicateCore-iOS-SDK.podspec
- Updated pod version
- updated changelog
> Version update to 1.0.7

- Sources/include/ALApplozicSettings.h
- Sources/prefrence/ALApplozicSettings.m
- Added a methods to save & get latest language selected (by user) for Speech To Text (STT)
> [CM-1348] Added Support for multiple languages in STT

- CHANGELOG.md
- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Target Support Files/KommunicateCore-iOS-SDK/KommunicateCore-iOS-SDK-Info.plist
- KommunicateCore-iOS-SDK.podspec
- upgraded pod version
- updated changelog with release details
> upgraded pod version

- Example/Podfile.lock
- Sources/message/ALMessageClientService.m
- Updated delete conversation endpoint & response as per new new api which is used in web
> [CM-1352] Delete Conversation at User End

- CHANGELOG.md
- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Target Support Files/KommunicateCore-iOS-SDK/KommunicateCore-iOS-SDK-Info.plist
- KommunicateCore-iOS-SDK.podspec
- Updated Pod version to 1.0.9
- Updated changelog
> Updated Pod version to 1.0.9

- Sources/include/ALRegisterUserClientService.h
> Increased version code

- CHANGELOG.md
- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Target Support Files/KommunicateCore-iOS-SDK/KommunicateCore-iOS-SDK-Info.plist
- KommunicateCore-iOS-SDK.podspec
- Updated pod version to 1.1.0
- Updated changelog
> Updated Pod version

- CHANGELOG.md
- Sources/account/ALRegisterUserClientService.m
- Sources/include/ALUser.h
- Platform property is added in ALUser
- Enum is added for accessing value of different platform
- Added default value for platform inside ALRegisterUserClientService
> [CM-1282] Added platform property and Enum for platform in ALUser

- Sources/prefrence/ALApplozicSettings.m
##Summary
Fixed attachment not able to send in IOS Agent App
> Crash fix on agent app attachment sent

- CHANGELOG.md
- Sources/include/ALMessage.h
- Sources/message/ALMessage.m
- Added a instance of isAutoSuggestion to check the message is Auto Suggestion Message or not
- Created a function to extract AutoSuggestion data from the meta data.
> [CM-1341] Added Support For Auto Suggestions Rich Message

- CHANGELOG.md
- Sources/JWT/user/ALUserClientService.m
Added elastic update support for email updation in IOS SDK
> Fixed API call for email updation in IOS SDK

- Sources/include/ALApplozicSettings.h
- Sources/prefrence/ALApplozicSettings.m
- Creates functions to save single threaded flag in local
> [CM-1676] Upgraded appsetttings api & optimised the create conversation flow

- Sources/applozickit/ALMQTTConversationService.m
- Sources/include/ALMessage.h
- Sources/message/ALMessage.m
- Added support for conversation deletion(from dashboard) sync
> Added support for procession conversation deletion message

- Sources/account/ALRegisterUserClientService.m
- Added App Module Name in Update Api Call for iOS Agent App.
> [CM-2060] Push Notification failure after update Api Call | iOS Agent App

- Sources/include/ALUserDefaultsHandler.h
- Sources/prefrence/ALUserDefaultsHandler.m
- Added imageURL in user defaults. 
- Added contactNumber in user defaults.
- Added RoleInOrganisation in user defaults.
> [CM-2068] Edit Profile Flow Screen | iOS Agent App

- Sources/include/ALUtilityClass.h
- Sources/include/TSMessageView.h
- Sources/push/TSMessageView.m
- Sources/utilities/ALUtilityClass.m
Reverts Kommunicate-io/KommunicateCore-iOS-SDK#88
tap gesture recogniser not working
> Revert "[CM-1827] In App Notification Banner Colour Customization"

- Sources/include/ALMessageService.h
- Sources/sync/ALSyncCallService.m
- Added a notification for message metadata update and a check for Message Delete.
> [CM-1121] Delete message with sync - iOS Agent App and SDK

- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Pods.xcodeproj/project.pbxproj
- KommunicateCore-iOS-SDK.podspec
- Sources/KommunicateCore-Info.plist
- Updated the pod file.
- As well as updated the value of `CFBundleShortVersionString` to latest `1.2.3`.
> Updated podFile to 1.2.3

- CHANGELOG.md
- Example/Podfile.lock
- KommunicateCore-iOS-SDK.podspec
- Sources/KommunicateCore-Info.plist
- Api call optimisations.
- Updated Pod Version to 1.2.4
> Updated Podfile to 1.2.4

- CHANGELOG.md
- Example/Podfile.lock
- Example/Pods/Local Podspecs/KommunicateCore-iOS-SDK.podspec.json
- Example/Pods/Manifest.lock
- KommunicateCore-iOS-SDK.podspec
- Sources/KommunicateCore-Info.plist
- Updated the version to 1.2.5
> Updated PodFile to 1.2.5
